format = """
$username\
$directory\
$git_branch\
$fill\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$conda\
$python\
$time\n  \
[󱞪](fg:magenta) \
"""

[directory]
format = "[](fg:white)[ $path ]($style)[](fg:white) "
style = "bg:white fg:black"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[fill]
style = "fg:black"
symbol = " "

[git_branch]
format = "[](fg:white)[ $symbol $branch ]($style)[](fg:white) "
style = "bg:white fg:black"
symbol = ""

[username]
disabled = false
format = "[](fg:cyan)[ 󰘳 $user ]($style)[](fg:cyan) "
show_always = true
style_root = "bg:cyan fg:black"
style_user = "bg:cyan fg:black"

# Languages

[c]
style = "bg:cyan fg:green"
format = " [](fg:cyan)[ $symbol$version ]($style)[](fg:cyan)"
disabled = false
symbol = " "

[elixir]
style = "bg:cyan fg:green"
format = " [](fg:cyan)[ $symbol$version ]($style)[](fg:cyan)"
disabled = false
symbol = " "

[elm]
style = "bg:cyan fg:green"
format = " [](fg:cyan)[ $symbol$version ]($style)[](fg:cyan)"
disabled = false
symbol = " "

[golang]
style = "bg:cyan fg:green"
format = " [](fg:cyan)[ $symbol$version ]($style)[](fg:cyan)"
disabled = false
symbol = " "

[haskell]
style = "bg:cyan fg:green"
format = " [](fg:cyan)[ $symbol$version ]($style)[](fg:cyan)"
disabled = false
symbol = " "

[java]
style = "bg:cyan fg:green"
format = " [](fg:cyan)[ $symbol$version ]($style)[](fg:cyan)"
disabled = false
symbol = " "

[julia]
style = "bg:cyan fg:green"
format = " [](fg:cyan)[ $symbol$version ]($style)[](fg:cyan)"
disabled = false
symbol = " "

[nodejs]
style = "bg:cyan fg:green"
format = " [](fg:cyan)[ $symbol$version ]($style)[](fg:cyan)"
disabled = false
symbol = "󰎙 "

[nim]
style = "bg:cyan fg:green"
format = " [](fg:cyan)[ $symbol$version ]($style)[](fg:cyan)"
disabled = false
symbol = "󰆥 "

[rust]
style = "bg:cyan fg:green"
format = " [](fg:cyan)[ $symbol$version ]($style)[](fg:cyan)"
disabled = false
symbol = " "

[scala]

style = "bg:cyan fg:green"
format = " [](fg:cyan)[ $symbol$version ]($style)[](fg:cyan)"
disabled = false
symbol = " "

[python]
style = "bg:cyan fg:green"
format = " [](fg:cyan)[ $symbol$version ]($style)[](fg:cyan)"
disabled = false
symbol = ' '

[conda]
style = "bg:cyan fg:green"
format = " [](fg:cyan)[ $symbol$environment ]($style)[](fg:cyan)"
disabled = false
symbol = '🅒 '
