# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$git_branch\n \
[󱞪](fg:magenta) \
"""
[username]
disabled = false
format = "[](fg:blue)[ 󰘳 $user ]($style)[](fg:blue) "
show_always = true
style_root = "bg:blue fg:black"
style_user = "bg:blue fg:black"

[directory]
format = "[](fg:bright-black)[ $path ]($style)[](fg:bright-black) "
style = "bg:bright-black fg:blue"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:bright-black)[ $symbol $branch ]($style)[](fg:bright-black) "
style = "bg:bright-black fg:blue"
symbol = ""

