# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$git_branch\n \
[󱞪](fg:bright-black) \
"""
[username]
disabled = false
format = "[](fg:white)[ 󰘳 $user ]($style)[](fg:white) "
show_always = true
style_root = "bg:white fg:black"
style_user = "bg:white fg:black"

[directory]
format = "[](fg:black)[ $path ]($style)[](fg:black) "
style = "bg:black fg:white"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](fg:black)[ $symbol $branch ]($style)[](fg:black) "
style = "bg:black fg:white"
symbol = ""

